### ISSUE TITLE
Installation of lasR R package

### ISSUE THREAD

**Issue by samuelgrubinger** [MAAP-Project/ZenHub#1136]
This package, https://github.com/r-lidar/lasR, is a new open-source development from the author of lidR that is programmed for efficient pipeline processing of point clouds. It will likely be essential for GEO-TREES data processing. Currently, it is not on conda-forge and cannot be installed in R on MAAP. Any solutions?

**Comment by wildintellect** [comment]
The easiest path might be to build a conda-forge feedstock, at a minimum we can learn a lot from the lidR feedstock https://github.com/conda-forge/r-lidr-feedstock/blob/main/recipe/meta.yaml

**Comment by wildintellect** [comment]
I just tested on https://hub.openveda.cloud which uses [Rocker images](https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/binder_4.3.3.Dockerfile) (includes GDAL), and this build fine with
```
install.packages('lasR', repos = 'https://r-lidar.r-universe.dev')
```
Which is not surprising since the core is Ubuntu, build tools are included, and conda is not involved. Just noting here as a temporary option, if it's needed soon.

Also noted on Slack that PDAL pipelines might be capable of similar workflows. One concern with lidR and lasR is the custom read/write modules and the lack of full COPC support. Not blockers just things to be aware of.

**Comment by samuelgrubinger** [comment]
Thanks Alex! I'll give it a shot.


*Samuel Grubinger*
Postdoctoral researcher
University of Maryland
He/him/his
***@***.***

**Comment by wildintellect** [comment]
Following next line of thought:
I hacked grayskull and generated a meta.yaml for building a conda package (still testing if it works)
r-lasr/meta.yaml
```
{% set name = "lasr" %}
{% set version = "0.10.3" %}
{% set posix = "m2-" if win else "" %}
{% set native = "m2w64-" if win else "" %}

package:
  name: r-{{ name }}
  version: '{{ version }}'

source:
  url: https://r-lidar.r-universe.dev/src/contrib/lasR_{{ version }}.tar.gz
  sha256: 147f2c50e30c2d5d9f7386be4fb12c12c9cf401bcb288f1e541faf9701db4499

build:
  number: 0
  merge_build_host: true
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - autoconf  # [unix]
    - "{{ compiler('c') }}"  # [unix]
    - "{{ compiler('m2w64_c') }}"  # [win]
    - "{{ compiler('cxx') }}"  # [unix]
    - "{{ compiler('m2w64_cxx') }}"  # [win]
    - posix  # [win]
  host:
    - r-base
    # - r-methods
    # - r-stats
    - r-r.utils
  run:
    - r-base
    # - r-methods
    # - r-stats
    - r-r.utils

test:
  commands:
    - $R -e "library('lasR')"  # [not win]
    - "\"%R%\" -e \"library('lasR')\""  # [win]

about:
  home: https://github.com/r-lidar/lasR
  summary: Fast and pipeable airborne lidar processing tools. Read/write 'las' and 'laz' files, computation of metrics in area based approach, point filtering, normalization, individual tree segmentation and other manipulations in a powerful and versatile processing chain.
  license: NGPL

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
```
conda build needed version, hard coded for now

```
conda install -c conda-forge conda-libmamba-solver
conda build -c conda-forge r-lasr
```

Had to comment out r-methods and r-stats, core packages? then rename r-r.utils
stuck now on 
```
ValueError: Incompatible component merge:
  - 'h193b22a_2'
  - 'h4bf12b8_2'
 ```
