### ISSUE TITLE
Enable SSH feature in Che 7 workspaces

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#242]
Because Che 7 doesn't follow the conventions of Che 6, there's going to be some refactoring needed:

- [x] Installed `openssh-server` as part of the jupyter_image using `apt-get install openssh-server`
- [x] Run the ssh server in the background, add the lines `service ssh start` right before starting jupyter in `entrypoint.sh`
- [x] Edit the `show_ssh_info` extension to remove the check for an `ssh` agent. Should still give a warning about missing ssh keys.
- [x] The namespace of the workspace is now `<username>-<workspaceid>`. In the code that looks up the external NodePort via Kubernetes URL, concatenate the `CHE_WORKSPACE_NAMESPACE` and `CHE_WORKSPACE_ID` environment variables together.
- [x] In a clustered configuration, the IP address for the external SSH port is still tied to the master Kubernetes node, not the IP address of the worker node. I propose just getting the hostname from the `CHE_API_EXTERNAL` environment variable to use instead of an IP address.

To test the kubernetes URL in jupyter's terminal, use the following command below. You'll need to apt-get install curl first.
```
TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`; curl -kD - -H "Authorization: Bearer $TOKEN" https://kubernetes.default:443/api/v1/namespaces/$CHE_WORKSPACE_NAMESPACE-$CHE_WORKSPACE_ID/services/ws 2>/dev/null | grep nodePort | awk '{print $2}'
```

**Comment by mayadebellis** [comment]
@gchang Running `TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`; curl -kD - -H "Authorization: Bearer $TOKEN" https://kubernetes.default:443/api/v1/namespaces/$CHE_WORKSPACE_NAMESPACE-$CHE_WORKSPACE_ID/services/ws 2>/dev/null` in the terminal (after starting the ssh service and installing curl) I get an error.
![image.png](https://images.zenhubusercontent.com/5ee967d942152fe068604fa1/3e5996bb-5d2f-43ce-b393-4b5b277ef906)

Did this work fine in the workspace terminal for you?

**Comment by gchang** [comment]
Ah, you'll need to launch a custom workspace BUT that can only happen after you launch a "Getting Started" workspace. So the process right now is:
1) Launch MAAP Stable
2) Edit that workspace's dev file with the Kubernetes one (@bsatoriu do you have the latest one with the latest docker image)
3) Save and restart the workspace!

The reason we need this is because of a bug in workspace create. We need to use the WorkspaceID to randomize the Kubernetes namespace. However, if you launch a custom workspace from scratch, it'll error out because it checks the namespace string BEFORE it even issues a workspace id. Using a "Get Started" workspace follows a different validation path, so it successfully launches and sets the Kubernetes namespace to username-workspaceid. Now, once it successfully launches, you can THEN set the custom dev file and restart because the workspace ID already exists.

**Comment by gchang** [comment]
I believe this will be unnecessary once we make the Kubernetes dev file on of the "Get Started" ones, but for now, this is how you would test new stacks/devfiles.

**Comment by gchang** [comment]
FYI, this is the one I've been using as of last week. You'll need to substitute it with a newer jupyter_image.
```
apiVersion: 1.0.0
metadata:
  name: basic-gu02p
attributes:
  editorFree: 'true'
components:
  - endpoints:
      - attributes:
          type: ide
          discoverable: 'false'
          path: /
          public: 'true'
          protocol: http
        name: jupyter
        port: 3100
    referenceContent: |
      kind: List
      items:
        - apiVersion: v1
          kind: Pod
          metadata:
            name: ws
            labels:
              name: ws
          spec:
           containers: 
            - name: jupyter
              image: 'mas.maap-project.org:5000/root/jupyter_image/gchang-maap-che7:latest'
              imagePullPolicy: Always
              resources:
                limits:
                  memory: 2048Mi
              securityContext:
                privileged: true
        - apiVersion: v1
          kind: Service
          metadata:
            name: ws
          spec:
            type: NodePort
            ports:
              - port: 22
          selector:
            name: ws
    type: kubernetes
    alias: maap-jupyterlab
    env:
      - value: WS_JUPYTER
        name: MACHINE_NAME
```

**Comment by bsatoriu** [comment]
I verified this is working on UAT. Same as George's, with a different workspace name, "custom-devfile", and the latest vanilla:develop image.

```
apiVersion: 1.0.0
metadata:
  name: custom-devfile
attributes:
  editorFree: 'true'
components:
  - endpoints:
      - attributes:
          type: ide
          discoverable: 'false'
          path: /
          protocol: http
          public: 'true'
        name: jupyter
        port: 3100
    referenceContent: |
      kind: List
      items:
        - apiVersion: v1
          kind: Pod
          metadata:
            name: ws
            labels:
              name: ws
          spec:
           containers: 
            - name: jupyter
              image: 'registry.nasa.maap.xyz/root/jupyter_image/vanilla:develop'
              imagePullPolicy: Always
              resources:
                limits:
                  memory: 2048Mi
              securityContext:
                privileged: true
        - apiVersion: v1
          kind: Service
          metadata:
            name: ws
          spec:
            type: NodePort
            ports:
              - port: 22
          selector:
            name: ws
    type: kubernetes
    reference: 'https://gchang.com/gchang-maap-che7.yaml'
    alias: maap-jupyterlab
    env:
      - value: WS_JUPYTER
        name: MACHINE_NAME

```
