### ISSUE TITLE
Update hyperlink styles

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#401]
The "Read More" hyperlink styles do not match other hyperlink styles used on the site.

**Comment by anilnatha** [comment]
Adding the following lines of CSS has resolved this issue.

```css
.ab-block-post-grid .ab-block-post-grid-more-link {
	color: var(--color-blue-dark);
}
```

This issue has been resolved on GCC and Pilot Ops.  Awaiting resolution of `custom.css` write issues on UAT and DIT to complete task.
