### ISSUE TITLE
Search/Visualize iframes are cutoff

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#450]
The Search and Visualize pages are cutoff at the top and are not aligning to the bottom.  The issue exists in all environments.

<img width="1920" alt="Screen Shot 2021-09-16 at 13 38 11" src="https://user-images.githubusercontent.com/931107/133682582-addc0799-66de-49db-ae00-a019b0d66c4b.png">

<img width="1920" alt="Screen Shot 2021-09-16 at 13 38 32" src="https://user-images.githubusercontent.com/931107/133682613-4de750d5-f28d-4b08-aab0-263c7f2619dc.png">

**Comment by anilnatha** [comment]
After reviewing additional pages, it appears that all pages are affected by this issue, not just the search and visualize pages.

**Comment by anilnatha** [comment]
Changing the following CSS in `custom.css` has resolved the issue

##### From:

```css
.page-template-blocks .site-inner, .site-inner {
    margin-top: 10px;
    margin-bottom: 10px;
}
```

##### To:

```css
.page-template-blocks .site-inner, .site-inner {
    margin-top: 95px;
    margin-bottom: 10px;
}
```

The change has been applied to GCC and Pilot OPS.  I'm awaiting an update to the file permissions for `custom.css` in UAT and DIT so I can synchronize the change to those environments.
