### ISSUE TITLE
Update design of profile page

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#509]
With the profile page now accessible (DIT/UAT), enhancements can be made to improve usability and aesthetics.

@gchang @bsatoriu:
To get started, one of the fields we display is `status`. Do we have any documentation that lists all of the possible status values and what they mean?  I think it would be useful to inform users of what the status messages mean, especially if they have a status like "suspended", which is what mine shows in DIT at the moment.

**Comment by anilnatha** [comment]
Updated design has been implemented and available in DIT.  One oustanding issue exists, need to know the URLs for the ESA (Gluu) environments. Once I add those URLs, the next step is to rollout to UAT for Sri to test.

<img width="1280" alt="Screen Shot 2022-03-03 at 13 21 33" src="https://user-images.githubusercontent.com/931107/156654865-b9a1148d-e70a-4d59-abe5-fbbebd0f266c.png">

**Comment by anilnatha** [comment]
@oddes The updated design has been rolled out to UAT and is ready for testing.  After testing is done, if everything is good, I'll submit a PR for the changes in the Authorizer repo where this code exists.

**Comment by anilnatha** [comment]
For the rollout to production, the following CSS needs to be added to `custom.css` along with copying the contents of the maapprofile file to the maap profile wordpress template in WP Theme Editor.

```css
.container-border {
	border: 1px solid #F2F2F2;
}

.icon-size-lg {
	font-size: 16px;
}

.icon-margin-right {
	margin-right: 8px
}

#profile-details {
	word-break: normal;
}

#profile-details tr td {
	padding: 12px;
	vertical-align: top;
}

#profile-details tr td:first-child {
	width: 25%;
}

.success-text {
	color: var(--color-green-light);
}

.error-text {
	color: var(--color-red-light);
}
```
