### ISSUE TITLE
Cursor doesn't change when accordions are hovered.

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#520]
Users may not know that accordion block elements are clickable because the cursor doesn't change to a pointer when they are hovered.

**Comment by anilnatha** [comment]
By adding the following CSS to `custom.css` the issue is resolved on DIT, UAT, and OPS.

```css
/* Add cursor pointer for accordions to indicate they are clickable */
.ab-block-accordion .ab-accordion-title {
	cursor: pointer;
}
```
