### ISSUE TITLE
jobs UI: when submitting a job, have contextual help about what each input does

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/ZenHub#658]
Jobs UI Usability test:

The job-submit form should be self-documenting. If you have custom fields then the file to define which fields you have should also let you define a definition/help for each field to help others (and yourself) remember what everything is.
e.g. is "input_file" a MAAP file? Any file? netCDF only? etc.

**Comment by marjo-luc** [comment]
The inputs to an algorithm are defined by the algorithm developer in the algorithm_config.yaml. The jobs UI does not have any information beyond what is provided in this file.

For example, in this algorithm_config.yaml, there is an input named "input_file." There is no description of the input, no indication of valid/invalid values, no indication whether this input is required or optional, etc., so that information cannot be conveyed to the user through the jobs ui.

```
algo_name: run-dps-test
version: main
environment: ubuntu
repository_url: https://repo.dit.maap-project.org/root/dps-unit-test.git
docker_url: mas.maap-project.org:5000/root/ade-base-images/vanilla:latest
# queue chosen when registering
queue: maap-dps-worker-16gb

# fill out these fields
# explain what this algorithm does
description: 
# path to the wrapper script for running the algorithm
run_command: dps-unit-test/run-test.sh
# set a storage value in GB or MB or KB, e.g. "100GB", "20MB", "10KB"
disk_space: 5GB
inputs:
# remove below this line if no inputs
# rename and set algorithm input names accordingly
  - name: input_file
    download: True
```
