### ISSUE TITLE
Update workspace `devfile.yaml` branch reference

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#682]
Since renaming `dit` to `develop` in our maap-workspace repo, our image builds continue to reference `dit` in each workspace's respective `devfile.yaml`. For example, in `maap-workspaces/devfiles/vanilla/devfile/devfile.yaml` we have:

```yaml
containers:
 - name: jupyter
   image: 'mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:dit'
```

Which should be:

```yaml
containers:
 - name: jupyter
   image: 'mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:develop'
```
